"""Evidence chain audit — scan a research report for evidence quality."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .evidence_chain import get_evidence_by_id, query_events


@dataclass
class AuditResult:
    cited_ids: list[str] = field(default_factory=list)
    fake_ids: list[str] = field(default_factory=list)
    unused_ids: list[str] = field(default_factory=list)
    supported_count: int = 0
    inferred_count: int = 0
    unverified_count: int = 0
    bare_sentence_count: int = 0
    bare_sentence_examples: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    ok: bool = True

    @property
    def total_claims(self) -> int:
        return self.supported_count + self.inferred_count + self.unverified_count


_EVIDENCE_ID_PATTERN = re.compile(r"\[(ev_[^\]]+|E\d+(?:-img)?)\]")
_INFERRED_PATTERN = re.compile(r"\[(?:推断|Inferred)\]")
_UNVERIFIED_PATTERN = re.compile(r"\[(?:待验证|Needs Verification)\]")
_ANY_ANNOTATION = re.compile(r"\[(?:ev_|E\d|推断|Inferred|待验证|Needs Verification)")
_SENTENCE_SEP = re.compile(r"[。.！!？?\n]+")
_ABBREV = re.compile(
    r"\b(?:et al|etc|i\.e|e\.g|vs|fig|Fig|Eq|eq|al|cf|Dr|Prof|Mr|Ms|vs)\."
)
_DECIMAL = re.compile(r"(\d+)\.(\d)")


def _is_annotation_only(text: str) -> bool:
    stripped = _ANY_ANNOTATION.sub("", text).strip()
    return len(stripped) < 5


def _split_sentences(text: str) -> list[str]:
    # Protect decimal numbers and abbreviations before splitting on dots
    protected = _DECIMAL.sub(r"\1__DOT__\2", text)
    protected = _ABBREV.sub(
        lambda m: m.group(0).replace(".", "__DOT__"),
        protected,
    )
    raw = _SENTENCE_SEP.split(protected)
    restored = [s.replace("__DOT__", ".").strip() for s in raw]
    return [s for s in restored if len(s) > 8]


def _evidence_ids_in_text(text: str) -> list[str]:
    return [m.group(1) for m in _EVIDENCE_ID_PATTERN.finditer(text)]


def _collect_known_ids(quest_root: Path) -> set[str]:
    known: set[str] = set()
    entries = query_events(quest_root)
    for entry in entries:
        eid = str(entry.get("evidence_id") or "").strip()
        if eid:
            known.add(eid)
    return known


def _entry_source_label(entry: dict[str, Any]) -> str:
    tool = str(entry.get("tool_name") or "tool")
    source_ref = entry.get("source_ref") if isinstance(entry.get("source_ref"), dict) else {}
    kind = str(source_ref.get("kind") or "")
    path = str(source_ref.get("path") or "")
    page = source_ref.get("page")
    line = source_ref.get("line")
    url = str(source_ref.get("url") or "")

    parts = [f"tool={tool}"]
    if kind:
        parts.append(f"kind={kind}")
    if url and url != "None":
        parts.append(url)
    elif path:
        loc = path
        if page is not None:
            loc += f" p.{page}"
        if line is not None:
            loc += f" L{line}"
        parts.append(loc)
    else:
        parts.append("(no location)")
    return " | ".join(parts)


def _entry_evidence_summary(entry: dict[str, Any]) -> str:
    preview = str(entry.get("output_preview") or entry.get("summary") or "")
    if len(preview) > 200:
        preview = preview[:197].rstrip() + "..."
    return preview or "(no content)"


def audit_report(report_text: str, quest_root: Path | str) -> AuditResult:
    """Scan a research report against evidence_store.json.

    Args:
        report_text: The full report text generated by the agent.
        quest_root: Path to the quest root directory (contains .ds/evidence/evidence_store.json).

    Returns:
        AuditResult with counts, issues, and verdict.
    """
    root = Path(quest_root)
    result = AuditResult()

    # Collect known evidence IDs from the store
    try:
        known_ids = _collect_known_ids(root)
    except Exception as exc:
        result.errors.append(f"Cannot read evidence_store: {exc}")
        result.ok = False
        return result

    if not known_ids:
        result.errors.append("evidence_store is empty — no evidence was recorded for this quest")
        result.ok = False

    # Extract cited evidence IDs from report
    result.cited_ids = _evidence_ids_in_text(report_text)

    # Detect fake (non-existent) IDs
    for eid in result.cited_ids:
        if eid not in known_ids:
            result.fake_ids.append(eid)

    # Detect unused evidence (recorded but never cited)
    cited_set = set(result.cited_ids)
    for eid in known_ids:
        if eid not in cited_set:
            entry = get_evidence_by_id(root, eid)
            if entry and str(entry.get("status") or "") == "ok":
                result.unused_ids.append(eid)

    # Count three-level classification
    sentences = _split_sentences(report_text)
    for sent in sentences:
        if _is_annotation_only(sent):
            continue
        has_evidence = bool(_EVIDENCE_ID_PATTERN.search(sent))
        has_inferred = bool(_INFERRED_PATTERN.search(sent))
        has_unverified = bool(_UNVERIFIED_PATTERN.search(sent))

        if has_evidence:
            result.supported_count += 1
        elif has_inferred:
            result.inferred_count += 1
        elif has_unverified:
            result.unverified_count += 1

    # Find bare claims (no annotation at all, not just annotation text)
    bare: list[str] = []
    for sent in sentences:
        if _is_annotation_only(sent):
            continue
        if not _ANY_ANNOTATION.search(sent):
            bare.append(sent)
    result.bare_sentence_count = len(bare)
    result.bare_sentence_examples = bare[:5]

    # Verdict
    has_issues = bool(result.fake_ids) or result.bare_sentence_count > 2
    result.ok = not has_issues and bool(result.cited_ids)

    return result


def render_audit_markdown(audit: AuditResult, quest_root: Path | str | None = None) -> str:
    """Render an AuditResult as a human-readable Markdown report."""
    root = Path(quest_root) if quest_root else None

    lines = [
        "## Evidence Chain Audit",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Evidence IDs cited | {len(audit.cited_ids)} |",
        f"| Supported claims [E...] | {audit.supported_count} |",
        f"| Inferred claims [推断] | {audit.inferred_count} |",
        f"| Unverified claims [待验证] | {audit.unverified_count} |",
        f"| Total annotated claims | {audit.total_claims} |",
        f"| Bare claims (no annotation) | {audit.bare_sentence_count} |",
        f"| Verdict | **{'PASS' if audit.ok else 'WARN'}** |",
        "",
    ]

    if audit.fake_ids:
        lines.append("### Referenced but non-existent evidence IDs")
        lines.append("")
        for eid in audit.fake_ids:
            lines.append(f"- `{eid}`")
        lines.append("")

    if audit.unused_ids:
        lines.append("### Recorded but never cited evidence")
        lines.append("")
        for eid in audit.unused_ids[:10]:
            label = eid
            if root:
                entry = get_evidence_by_id(root, eid)
                if entry:
                    label = f"{eid} — {_entry_source_label(entry)}"
            lines.append(f"- {label}")
        if len(audit.unused_ids) > 10:
            lines.append(f"- ... and {len(audit.unused_ids) - 10} more")
        lines.append("")

    if audit.bare_sentence_examples:
        lines.append("### Bare claims (no evidence annotation)")
        lines.append("")
        for i, sent in enumerate(audit.bare_sentence_examples, 1):
            preview = sent[:200].rstrip() + "..." if len(sent) > 200 else sent
            lines.append(f"{i}. {preview}")
        lines.append("")

    if audit.errors:
        lines.append("### Errors")
        lines.append("")
        for err in audit.errors:
            lines.append(f"- {err}")
        lines.append("")

    if audit.ok and not audit.errors:
        lines.append("All cited evidence IDs are valid and most claims are annotated.")
        lines.append("")

    return "\n".join(lines)


def build_evidence_table(report_text: str, quest_root: Path | str) -> str:
    """Build a Markdown evidence table from cited IDs in the report.

    This complements the table the model generates — it uses the actual
    evidence_store to provide ground-truth source locations.
    """
    root = Path(quest_root)
    cited_ids = _evidence_ids_in_text(report_text)
    if not cited_ids:
        return "*(No evidence IDs found in report)*"

    lines = [
        "| Evidence ID | Tool | Source Location | Content | Status |",
        "|-------------|------|-----------------|---------|--------|",
    ]
    seen: set[str] = set()
    for eid in cited_ids:
        if eid in seen:
            continue
        seen.add(eid)
        entry = get_evidence_by_id(root, eid)
        if entry is None:
            lines.append(f"| `{eid}` | *(not found)* | — | — | — |")
            continue
        tool = str(entry.get("tool_name") or "?")
        source = _entry_source_label(entry)
        summary = _entry_evidence_summary(entry)
        status = str(entry.get("status") or "?")
        lines.append(f"| `{eid}` | {tool} | {source} | {summary} | {status} |")

    return "\n".join(lines)
